apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/saumeya/issue_17801.git
      revision: HEAD
      directories:
      - path: '*'
      - path: 'ingress-controllers'
        exclude: true
      - path: 'ingress-controllers/*'
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      syncPolicy:
        automated: {}
      project: 'default'
      source:
        repoURL: https://github.com/saumeya/issue_17801.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: 'in-cluster'
        namespace: '{{.path.basename}}'
